# server
[server]
host = "localhost"
port = 8000


# database
[database]
host = "rm-bp10k05378cuq9109wo.mysql.rds.aliyuncs.com"
port = 3306
user = "compass_bag_dev"
password = "CompassBag2024"
dbname = "compass_bag_dev"
