[package]
name = "mmacro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.77", features = ["extra-traits"] }
quote = "1.0.37"
proc-macro2 = "1.0.86"
darling = "0.20.10"
anyhow = "1.0.86"
askama = "0.12.1"
